general {
  before_sleep_cmd = /run/current-system/sw/bin/hyprlock
  before_suspend_cmd = /run/current-system/sw/bin/hyprlock
  after_sleep_cmd = systemctl --user restart pipewire pipewire-pulse wireplumber
}

# listener {
#   timeout = 100
#   on-timeout =  hyprlock
#   on-resume = hyprlock
# }

listener {
  timeout = 990
  on-timeout = brightnessctl -s set 10%
  on-resume = brightnessctl -r
}

listener {
  timeout = 1000
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 1000
	on-timeout = systemctl suspend-then-hibernate
  on-resume = $HOME/.current_wallpaper
}