# Shell variables
# Generated by 'wal'
wallpaper='{wallpaper}'

# Special
background='{background}'
foreground='{foreground}'
cursor='{cursor}'

# Colors
color0='{color0}'
color1='{color1}'
color2='{color2}'
color3='{color3}'
color4='{color4}'
color5='{color5}'
color6='{color6}'
color7='{color7}'
color8='{color8}'
color9='{color9}'
color10='{color10}'
color11='{color11}'
color12='{color12}'
color13='{color13}'
color14='{color14}'
color15='{color15}'

  # --color=fg+:{foreground},bg+:{color2},hl+:{color4}
    
# export FZF_DEFAULT_COLORS_PYWAL="
#     --color=fg:{foreground},bg:{background},hl:{color1}
#     --color=fg+:{foreground},bg+:{color2},hl+:{color4}
#     --color=info:{color7},prompt:{color2},spinner:{color1}
#     --color=pointer:{background},marker:{color1},header:{color4}
# "

# export FZF_DEFAULT_COLORS_PYWAL="
#     --color=fg:{foreground},bg:{background},hl:{color3}
#     --color=fg+:{foreground},bg+:{color8},hl+:{foreground}
#     --color=info:{color8},prompt:{foreground},spinner:{color3}
#     --color=pointer:{foreground},marker:{foreground},header:{color3}
#     --color=border:{color8},gutter:{background}
# "

# Fix LS_COLORS being unreadable.
export LS_COLORS="${{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"
