background = {background}
foreground = {foreground.darken(55)}
cursor-color = {cursor}
cursor-text = {background}
selection-foreground = {foreground.darken(28)}
selection-background = {foreground.darken(87)}
palette = 0={color0}
palette = 1={color1.darken(5)}
palette = 2={color2.darken(5)}
palette = 3={color3.darken(5)}
palette = 4={color4}
palette = 5={color5.darken(5)}
palette = 6={color6.darken(5)}
palette = 7={foreground.darken(22)}
palette = 8={foreground.darken(69)}
palette = 9=#8b4049
palette = 10=#4a8b5e
palette = 11={color3}
palette = 12={color4}
palette = 13={color5}
palette = 14={color6}
palette = 15={foreground.darken(9)}
