set -g status-left-style "fg={foreground.darken(35)},bg=default"
set -g status-style "fg={foreground.darken(48)},bg={foreground.darken(90)}"

set -g window-status-current-style "fg=#c9a35b,bg=default,bold"

set -g window-status-style "fg={foreground.darken(32)},bg=default"

set -g window-status-activity-style "fg={color3.darken(48)},bg=default"

set -g pane-border-style "fg={foreground.darken(84)}"
set -g pane-active-border-style "fg={color4.darken(9)}"

set -g status-right-style "fg={foreground.darken(35)},bg=default"

set -g message-style "fg={foreground.darken(22)},bg={foreground.darken(80)}"
set -g message-command-style "fg={foreground.darken(22)},bg={foreground.darken(80)}"

set -gw mode-style "fg={foreground.darken(28)},bg={foreground.darken(87)}"
