#!/usr/bin/env python3

import subprocess
import sys
import time
from collections import defaultdict

time.sleep(0.5)

EINK_DATA = {
    "name":"desc:DSC Paperlike13K 0x00003400",
    "port":"HDMI-A-1"
}

SETTINGS = {
    "theme": "~/.config/wal/colorschemes/dark/eink.json",
    "default_wallpaper": "~/dot/files/assets/white-background.jpg",
}

WORKSPACES = ["1","2","3","4","5","6","7","8","9","10"]

def execute(command, args={}):
    default = {
        "shell": True,
        "capture_output": True,
        "text": True,
        "check": True,
    }
    try:
        return subprocess.run(command, **{**default, **args}).stdout.strip()
    except Exception as e:
        print(f"Error running command '{command}': {e.stderr}")

        raise e

def reset_to_default():
    execute(["hyprctl reload"])

def set_global_eink_theme():
    command = ["wal -n --theme", SETTINGS["theme"]]

    execute(" ".join(command))

def set_white_wallpaper():
    command =  [
        "swww img",
        "--transition-type none",
        f"--outputs {EINK_DATA['port']}",
        SETTINGS["default_wallpaper"],
    ]
    
    execute(" ".join(command))

def notify_success():
    execute(["notify-send", "E-ink connected", "Default settings are applied"])

def apps_running():
    command = execute("hyprctl clients -j | jq '.[] | (.workspace.name + \":\" + .initialClass)'")
    result = command.split('\n')

    mapping = defaultdict(list)

    for app in result:
        cleaned = app.replace('"', '')

        workspace, app_name = cleaned.split(":", 1)

        if workspace in mapping is False:
            mapping[workspace] = [app_name]
        else:
            mapping[workspace].append(app_name)

    return mapping

class BatchUpdateHyprland:
    def __init__(self):
        self.workspaces = self.__workspaces()
        self.hyprland_commands = []

    def add_hyprland_command_to_batch(self, rules, workspace):
        self.hyprland_commands.append(f"keyword workspace {workspace}, monitor:{EINK_DATA['name']}, {rules}")

    def update_hyprland_config_rules(self):
        for workspace in self.workspaces:
            execute(" ".join([
                "hyprctl keyword workspace",
                workspace,
                f", monitor:{EINK_DATA['name']},",
                "gapsin:2   ,", 
                "gapsout:15 ,",
                "rounding:5 ,",
                "shadow:0   ,",
                "bluring:0  ,",
                "animation:0  ,",
                "bordersize:2  ,",
            ]))

            # 0xFFE8E8E8 (A clear, very light gray)
            # 0xFFDCDCDC (Slightly darker, "gainsboro")
            # 0xFFF5F5F5 (Almost white, "whitesmoke")

            execute(" ".join([
                "hyprctl keyword windowrulev2",
                "'bordercolor 0xFF808080 0xFFF5F5F5,",
                "noanim,",
                f" onworkspace:{workspace}'"
            ]))

    def __hyprland_batch_execute(self):
        execute(["hyprctl --batch", "; ".join(self.hyprland_commands)])

    def relaunch_applications(self):
        pass

    def __count_monitors(self):
        result = execute( "hyprctl monitors -j | jq -r 'length'")

        return int(result)

    def __workspaces(self):
        if self.__count_monitors() > 1:
            return self.__get_workspaces().split("\n")
        else:
            return WORKSPACES

    def __get_workspaces(self):
        command = f"hyprctl workspaces -j | jq -r --arg mon {EINK_DATA["port"]} '.[] | select(.monitor == $mon) | .name'"

        return execute(command)

def __main__():
    reset_to_default()
    set_global_eink_theme()
    set_white_wallpaper()
    updater = BatchUpdateHyprland()
    updater.update_hyprland_config_rules()

__main__()


