#!/usr/bin/env bash

set -euo pipefail

LG_MONITOR="DP-1" # swww query

ORIENTATION="${1:-horizontal}"
DEFAULT_WALLPAPER="$HOME/dot/files/defaults/forest.jpg"

case "$ORIENTATION" in
  *rotated*)
    swww img --outputs  "$LG_MONITOR" "$DEFAULT_WALLPAPER"
  ;;
  *)
    swww img --outputs  "$LG_MONITOR" "$DEFAULT_WALLPAPER"
  ;;
esac

pkill waybar
while pgrep -x waybar >/dev/null; do sleep 0.05; done
waybar & disown

notify-send 'LG connected on $LG_MONITOR and settings applied'
