#!/usr/bin/env python3

import subprocess
import sys
import time

time.sleep(0.5)

MONITOR_MAP = {
  "EINK": "desc:DSC Paperlike13K 0x00003400",
  "LG": "desc:LG Electronics LG HDR 4K 0x00013533"
}
if len(sys.argv) == 1:
    print(f"Usage: {sys.argv[0]} ALIAS=ws,list [ALIAS2=ws,list ...]")
    print(f"Example: {sys.argv[0]} LG=1,2,3,4,5,6,7,8 EINK=9,0")
    sys.exit(1)

def send_notification(title, message, urgency="low"):
  subprocess.run(["notify-send", "-u", urgency, title, message], check=True)

def batch_commands():
    commands = []

    for arg in sys.argv[1:]:
        alias, list_str = arg.split('=', 1)

        monitor_name = MONITOR_MAP[alias]
        workspaces = list_str.split(',')

        for ws in workspaces:
            ws_id = ws.strip()

            if ws_id == "0":
                ws_id = "10"

            # commands.append(f"dispatch moveworkspacetomonitor {ws_id} {monitor_name}")
            commands.append(f"keyword workspace {ws_id},monitor:{monitor_name}")

            if monitor_name == MONITOR_MAP["EINK"]:
                commands.append(f"hyprctl keyword workspace {ws_id}, monitor:desc:DSC Paperlike13K 0x00003400, gapsin:2, gapsout:6, rounding:5, shadow:0, bluring:0, bordercolor:rgba(000000ff)")

    return "; ".join(commands)

try:
    subprocess.run(["hyprctl", "reload"], check=True)
    subprocess.run(["hyprctl", "--batch", batch_commands()], check=True)

    send_notification("Workspaces Arranged", "Office profile activated.")
except subprocess.CalledProcessError as e:
    print(f"Error executing hyprctl: {e}")
    send_notification("Arrange Workspaces Error", f"hyprctl failed: {e}", "critical")
