#!/usr/bin/env python3

import subprocess
import sys
from collections import defaultdict

# colors
# 0xFFE8E8E8 (A clear, very light gray)
# 0xFFDCDCDC (Slightly darker, "gainsboro")
# 0xFFF5F5F5 (Almost white, "whitesmoke")


EINK_COMMANDS = [
    "gapsin:2,",
    "gapsout:15,",
    "rounding:4,",
    "shadow:0,",
    "bluring:0,",
    "animation:0,",
    "bordersize:2,",
]

LG_COMMANDS = [
    # "gapsin:6,", "gapsout:17,", "rounding:4,", "shadow:0,", "bluring:3,", "animation:0,", "bordersize:2,",
]

EINK_WINDOWRULE_SETTINGS = [
    "'bordercolor 0xFF808080 0xFFF5F5F5,",
    "noanim,",
]

LG_WINDOWRULE_SETTINGS = [
]


MONITORS_CONFIG = {
    "home_office": [
        {
            "name": "desc:DSC Paperlike13K 0x00003400",
            "port": "HDMI-A-1",
            "workspaces": ["1","2","3","4","5","6","7"],
            "settings": EINK_COMMANDS,
            "windowrulev2_settings": EINK_WINDOWRULE_SETTINGS,
        },
        {
            "name":"LG Electronics LG HDR 4K 0x00013533",
            "port":"DP-1",
            "workspaces": ["8", "9", "0"],
            "settings": LG_COMMANDS,
            "windowrulev2_settings": LG_WINDOWRULE_SETTINGS,
        }

    ],

    "home_office_eink": [{
        "name": "desc:DSC Paperlike13K 0x00003400",
        "port": "HDMI-A-1",
        "workspaces": ["1","2","3","4","5","6","7", "8", "9", "0"],
        "settings": EINK_COMMANDS,
        "windowrulev2_settings": EINK_WINDOWRULE_SETTINGS,
    }],

    "home_office_lg": [{
        "name": "desc:DSC Paperlike13K 0x00003400",
        "port": "HDMI-A-1",
        "workspaces": ["1","2","3","4","5","6","7", "8", "9", "0"],
        "settings": LG_COMMANDS,
        "windowrulev2_settings": LG_WINDOWRULE_SETTINGS,
    }],
}

def execute(command, args={}):
    defaults = {
        "shell": True,
        "capture_output": True,
        "text": True,
        "check": True,
    }

    try:
        return subprocess.run(command, **{**defaults, **args}).stdout.strip()
    except Exception as e:
        print(f"Error running command '{command}': {e.stderr}")

        raise e

class BatchUpdateHyprland:
    def __init__(self, setup):
        self.setup = setup
        self.hyprland_commands = []

    # def add_hyprland_command_to_batch(self, rules, workspace):
    #     self.hyprland_commands.append(f"keyword workspace {workspace}, monitor:{EINK_DATA['name']}, {rules}")

    def update_hyprland_config_rules(self):
        for monitor_config in MONITORS_CONFIG[self.setup]:
            for workspace in monitor_config["workspaces"]:
                commands = [
                    "hyprctl keyword workspace",
                    workspace,
                    f", monitor:{monitor_config["name"]},",
                ].append(monitor_config["commands"])

                windowrulev2_commands = [
                    "hyprctl keyword windowrulev2",
                    *monitor_config["windowrulev2_commands"],
                    f" onworkspace:{workspace}'"
                ]

                execute(" ".join(commands))
                execute(" ".join(windowrulev2_commands))

    def __hyprland_batch_execute(self):
        execute(["hyprctl --batch", "; ".join(self.hyprland_commands)])

    def relaunch_applications(self):
        pass

    def __count_monitors(self):
        result = execute( "hyprctl monitors -j | jq -r 'length'")

        return int(result)

    # def __workspaces(self):
    #     if self.__count_monitors() > 1:
    #         return self.__get_workspaces().split("\n")
    #     else:
    #         return WORKSPACES

    # def __get_workspaces(self):
    #     pass
    # command = f"hyprctl workspaces -j | jq -r --arg mon {EINK_DATA["port"]} '.[] | select(.monitor == $mon) | .name'"

    # return execute(command)


def main():
    if len(sys.argv) <= 1:
        raise Exception("Please provide setup argument")

    # breakpoint()
    if sys.argv(1) in MONITORS_CONFIG.keys():
        raise Exception(f"Setup doesn't exist valid setups: {MONITORS_CONFIG.keys()}")


# updater = BatchUpdateHyprland()
# updater.update

if __name__ == "__main__":
    main()


