#!/usr/bin/env bash

start-waybar() {
  waybar -c "$HOME/.config/waybar/hosts/$(hostname).jsonc" &
  disown
}

pkill waybar
start-waybar

inotifywait -mr -e close_write,move,create,delete ~/.config/waybar |
  while read -r; do
    pkill waybar
    while pgrep -x waybar >/dev/null; do sleep 0.05; done
    start-waybar
  done
