#!/usr/bin/env bash
set -euo pipefail

# inspired by omarchy

DIR="$HOME/pictures/screenshots"
FILE="$DIR/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png"

if [[ ! -d "$DIR" ]]; then
	mkidr -p "$DIR"
fi

pkill slurp || hyprshot -m ${1:-region} --raw |
  satty --filename - \
    --output-filename "$FILE" \
    --early-exit \
    --action-on-enter save-to-clipboard \
    --save-after-copy \
    --copy-command 'wl-copy'