#!/usr/bin/env bash
set -euo pipefail

# props to https://github.com/BreadOnPenguins/scripts/blob/master/wallpapermenu

FOLDER=~/dot/wallpapers

pkill nsxiv || true

menu () {
  # CHOICE=$(nsxiv -otb $FOLDER/*)
  CHOICE=$(ls $FOLDER/* | shuf | xargs nsxiv -otb)

  case $CHOICE in
    *.*)
      swww img --transition-type wipe --transition-angle 45 --transition-duration 0.8 "$CHOICE"
      ln -sf "$CHOICE" ~/.current_wallpaper
      wal -i "$CHOICE"
    ;;
    *) exit 0 ;;
  esac
}

# If given arguments:
# First argument will be used by pywal as wallpaper/dir path
# Second will be used as theme (use wal --theme to view built-in themes)

case "$#" in
  0) menu ;;
  1) wal -i "$1" ;;
  2) wal -i "$1" --theme $2 ;;
  *) exit 0 ;;
esac