#!/usr/bin/env bash

# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer
# Fantastic script from ThePrimeagen

# search_directories=${SEARCH_DIRECTORIES_PATHS:-"$HOME/projects $HOME/obsidian $HOME/.config $HOME/dot"}
search_directories=${SEARCH_DIRECTORIES_PATHS:-"$HOME/projects $HOME/obsidian $HOME/.config $HOME/dot"}

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find $search_directories -mindepth 1 -maxdepth 1 -xtype d | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name