font_family      family="PragmataPro Nerd Font Mono" style="Regular"
bold_font        family="PragmataPro Nerd Font Mono" style="Bold"
italic_font      family="PragmataPro Nerd Font Mono" style="Italic"
bold_italic_font family="PragmataPro Nerd Font Mono" style="Bold Italic"
font_size        11.0

adjust_line_height 3

narrow_symbols U+E000-U+E09F,U+E0D8-U+F8FF,U+F0000-U+FFFFD,U+2665,U+26A1,U+2B58 1

# adjust_column_height 2

# use_system_wcwidth yes

text_composition_strategy legacy
# text_composition_strategy 1.0 0

# disable_ligatures cursor

modify_font baseline -1
modify_font cell_height 110%
modify_font cell_width 92%
