include font.conf

cursor_shape beam
cursor_blink_interval 0.0

# wayland fix for pasting screenshoots
paste_actions quote-urls-at-prompt,confirm 

scrollback_lines 10000
scrollback_pager less +G -R

click_interval 0.5
select_by_word_characters :@-./_~?&=%+#
mouse_hide_wait 0

# repaint_delay 2
# input_delay 0
# wayland_enable_ime no
sync_to_monitor yes

window_border_width 0
window_padding_width 5
confirm_os_window_close 0
enable_audio_bell no

single_instance yes
allow_remote_control yes
# listen_on unix:/tmp/kitty

macos_hide_titlebar yes
macos_option_as_alt yes

map ctrl+v               launch --type=background --allow-remote-control --keep-focus ${HOME}/.config/kitty/kitty-paste
map alt+left             send_text all \x1b\x62
map alt+right            send_text all \x1b\x66
map ctrl+shift+equal     increase_font_size
map ctrl+shift+minus     decrease_font_size
map ctrl+shift+backspace restore_font_size
map ctrl+shift+r         load_config_file

include ${HOME}/.cache/wal/colors-kitty-custom.conf
