# Group/Tabbed Windows Styling

group {
  groupbar {
    enabled = true

    gaps_in = 3
    height = 15
    priority = 3
    # stacked = true
    indicator_height = 4
    rounding = 10
    rounding_power = 4.0
    render_titles = true
    scrolling = true

    font_size = 12
    font_weight_active = bold
    font_weight_inactive = bold
    text_color = $foreground
    text_color_inactive = $foreground_dim

    col.active = $border_active1
    col.inactive = $color8

    col.locked_active = $color5
    col.locked_inactive = $color1
  }

  col.border_active = $border_active1
  col.border_inactive = $border_inactive

  col.border_locked_active = $color5 $color13 45deg
  col.border_locked_inactive = $color1
}

windowrule = match:group 1, no_anim on
animation = windowsOut, 0, 0, default 
