# See https://wiki.hyprland.org/Configuring/Permissions/

permission = .*/firefox, screencopy, allow
permission = .*/zoom, screencopy, allow
permission = .*/zoom-us, screencopy, allow

permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = .*wlx-overlay-s, screencopy, allow
