#!/usr/bin/env bash

set -euo pipefail

unset FZF_DEFAULT_OPTS FZF_CTRL_R_OPTS

fzf-with-options() {
  fzf \
    --ansi \
    --margin="1,1,1,1" \
    --cycle \
    --color="gutter:-1,border:238,scrollbar:238" \
    --prompt="> " \
    "$@"
}
    #--with-nth=2 \
		#--delimeter=":" \
    #--no-info \

export -f fzf-with-options
