#!/usr/bin/env bash

[[ "$(hostname)" != "homepc" ]] && exit 0

hyprctl keyword input:kb_model apple
hyprctl keyword input:kb_options "ctrl:swapcaps,ctrl:nocaps,grp:win_space_toggle"

ssh-add ~/.ssh/nixos
ssh-add ~/.ssh/id_rsa
ssh-add ~/.ssh/system_ed25519
