-- function _G.StatuslineMode()
-- 	local m = vim.fn.mode()
-- 	return (m == "n" and "[NORMAL]")
-- 		or (m == "i" and "[INSERT]")
-- 		or (m == "v" and "[VISUAL]")
-- 		or (m == "R" and "[REPLACE]")
-- 		or (m == "c" and "[C]")
-- 		or ""
-- end
--
-- function _G.PasteForStatusline()
-- 	return vim.o.paste and "🧷" or " 👾"
-- end
--
-- function _G.ReadOnly()
-- 	return vim.o.readonly or not vim.o.modifiable and "🔒" or ""
-- end
--
-- function _G.GitBranch()
-- 	local handle = io.popen("git branch --show-current 2>/dev/null")
-- 	if not handle then
-- 		return ""
-- 	end
-- 	local branch = handle:read("*a") or ""
-- 	handle:close()
-- 	branch = branch:gsub("\n", "")
-- 	return branch ~= "" and " " .. branch or ""
-- end
--
-- function _G.CocStatus()
-- 	local status = vim.g.coc_status or ""
-- 	return status == "" and "💤" or status
-- end
--
-- function _G.EncodingDisplay()
-- 	local enc = vim.o.fileencoding
-- 	local ff = vim.o.fileformat
-- 	return (enc ~= "utf-8" or ff ~= "unix") and string.format("[%s:%s]", enc, ff) or ""
-- end
--
-- function _G.TruncFile()
-- 	local width = vim.fn.winwidth(0)
--   local parent = vim.fn.fnamemodify(vim.fn.expand("%:h"), ":t")
--   local file   = vim.fn.expand("%:t:r")
--   local path   = parent .. "/" .. file
--
-- 	return width > 80 and path or vim.fn.expand("%:t:r")
-- end
--
-- -- function _G.ModeHighlight()
-- -- 	local m = vim.fn.mode()
-- -- 	if m == "n" then
-- -- 		vim.cmd("hi StatusLine guibg=black guifg=white")
-- -- 	elseif m == "i" then
-- -- 		vim.cmd("hi StatusLine guibg=black guifg=white")
-- -- 	elseif m == "v" then
-- -- 		vim.cmd("hi StatusLine guibg=black guifg=white")
-- -- 	end
-- -- end
--
-- -- ─── Autocommand for Mode-based Highlight ─────────────────────
--
-- -- vim.api.nvim_create_augroup("ModeColors", { clear = true })
-- -- vim.api.nvim_create_autocmd("ModeChanged", {
-- -- 	group = "ModeColors",
-- -- 	pattern = "*",
-- -- 	callback = _G.ModeHighlight,
-- -- })
--
-- -- ─── Statusline Setup ─────────────────────────────────────────
--
-- function _G.MyStatus()
-- 	local ft = vim.bo.filetype
-- 	if ft == "NvimTree" or ft == "aerial" then
-- 		return "" -- show nothing in those panes
-- 	end
--
-- 	-- ⬇️ everything you had before, verbatim ⬇️
-- 	return table.concat({
-- 		_G.StatuslineMode(),
-- 		_G.ReadOnly(),
-- 		_G.PasteForStatusline(),
-- 		" █" .. _G.GitBranch() .. "█ ",
-- 		" " .. _G.TruncFile(),
-- 		"%m",
-- 		"%=",
-- 		" " .. vim.bo.filetype,
-- 		" %l:%L",
-- 	}, "")
-- end
--
-- -- vim.o.statusline = "%{%v:lua.MyStatus()%}"
-- function _G.StatusHL()
-- 	local winid = vim.g.statusline_winid or vim.v.statusline_winid
-- 	return (winid == vim.api.nvim_get_current_win()) and "%#StatusLine#" or "%#StatusLineNC#"
-- end
--
-- vim.o.statusline = table.concat({
-- 	"%{%v:lua.StatusHL()%}",
-- 	"%{%v:lua.MyStatus()%}",
-- }, "")
--
-- vim.o.laststatus = 2
--
-- vim.api.nvim_create_autocmd({ "BufEnter", "WinEnter" }, {
-- 	pattern = { "NvimTree", "aerial" },
-- 	callback = function()
-- 		vim.opt_local.statusline = ""
-- 		vim.opt_local.winbar = ""
-- 	end,
-- })
-- --
-- -- vim.api.nvim_create_autocmd("ColorScheme", {
-- -- 	callback = function()
-- -- 		vim.cmd([[
-- -- 		  hi! StatusLine   guifg=#ffffff guibg=#000000 ctermfg=15 ctermbg=0 gui=NONE cterm=NONE
-- -- 		  hi! StatusLineNC guifg=#000000 guibg=#ffffff ctermfg=0  ctermbg=15 gui=NONE cterm=NONE
-- -- 		]])
-- -- 	end,
-- -- })
