#!/usr/bin/env bash

# Connected:
#           Magic Keyboard:
#               Address: 1C:1D:D3:74:6C:A9
#               Vendor ID: 0x004C
#               Product ID: 0x0320
#               Firmware Version: 3.1.4
#               Minor Type: Keyboard
#               RSSI: -46
#               Services: 0x800020 < HID ACL >

set -euo pipefail

MAC=${1:? "MAC required"}
NAME=${2:? "NAME required"}

TRIES=${3:-3}   # default 3
SLEEP=${4:-3}   # default 3

if bluetoothctl info "$MAC" | grep -q 'Connected: yes'; then
  echo "$NAME already connected"

  notify-send "Bluetooth" "$NAME already connected"
  exit 0
fi

# make adapter ready
bluetoothctl power on >/dev/null || true
bluetoothctl agent on >/dev/null || true
bluetoothctl default-agent >/dev/null || true
bluetoothctl trust "$MAC" >/dev/null || true

i=0
while [ "$i" -lt "$TRIES" ]; do
  i=$((i+1))
  echo "attempt connecting $i/$TRIES: connect $NAME"
  sleep 0.5
  if bluetoothctl connect "$MAC" | grep -q 'Connection successful'; then
    break
  fi

  # if adapter got wonky, nudge it
  if ! bluetoothctl show | grep -q 'Powered: yes'; then
    rfkill unblock bluetooth || true
    bluetoothctl power on || true
  fi

  sleep "$SLEEP"
done

if ! bluetoothctl info "$MAC" | grep -q 'Connected: yes'; then
  echo "Failed to connect to $2"
  notify-send "Bluetooth" "Failed to connect to $2"
  exit 1
fi

echo "$2 connected."
notify-send "Bluetooth" "$NAME connected."