set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'mrjones2014/smart-splits.nvim'

set -g @smart-splits_move_left_key  'None'
set -g @smart-splits_move_down_key  'None'
set -g @smart-splits_move_up_key    'None'
set -g @smart-splits_move_right_key 'None'

set -g @plugin 'Morantron/tmux-fingers'
set -g @plugin 'laktak/extrakto'

set -g @extrakto_grab_area 'window recent'
set -g @extrakto_split_direction 'p'

set -g @fingers-key f
# bind L run -b "#{@fingers-cli} start #{pane_id} --patterns line"
# set -g @fingers-pattern-line '^.+$'

set -g @fingers-pattern-git-recovery 'git (cherry-pick|rebase|revert|merge) --(abort|continue|skip)'
set -g @fingers-pattern-git-upstream 'git push --set-upstream .*'
set -g @fingers-pattern-branch       'On branch (?<match>.*)'
set -g @fingers-pattern-envvar       '^[A-Z0-9_]+=(?<match>.*)'
set -g @fingers-pattern-quoted       '"(?<match>[^"]+)"'
set -g @fingers-pattern-email        '[\w.+-]+@[\w-]+\.[\w.-]+'
set -g @fingers-pattern-mac          '([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}'
set -g @fingers-pattern-port         ':(?<match>\d{2,5})\b'
set -g @fingers-pattern-docker       '\b[0-9a-f]{12}\b'
set -g @fingers-pattern-jwt          'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+'
set -g @fingers-pattern-mdlink       '\[.+?\]\((?<match>[^)]+)\)'
set -g @fingers-pattern-semver       'v?\d+\.\d+\.\d+(-[\w.]+)?'
set -g @fingers-hint-style "fg=colour50,bold"
set -g @fingers-highlight-style "fg=colour179,underscore"

# Initialize TPM (keep at the very bottom)
run '~/.config/tmux/plugins/tpm/tpm'
