set -g default-terminal "tmux-256color"
# set -ag terminal-features ",xterm-kitty:RGB:sync:clipboard"
set-window-option -g mode-keys vi

set -sg escape-time 0
set -g base-index 1
set -g status-justify left
set -g status-position bottom
set -g aggressive-resize on
set -g allow-passthrough on
set -g set-clipboard on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set-option -g history-limit 10000
set -g mouse on
set -g focus-events on
set -s exit-empty on
set -g status-interval 5
set -g status-position bottom

set -g allow-rename off
set -g set-titles on

set -g set-titles-string 'tmux: kitty - #S'

set -g pane-border-indicators colour
set -g pane-border-status off
set -g pane-border-lines heavy


set -g window-style 'fg=default'
set -g window-active-style 'fg=default'

# Binds
unbind C-b
unbind -T prefix f
set -g prefix C-Space
bind C-Space send-prefix
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded."
bind c new-window -c "#{pane_current_path}"
bind x kill-pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind -r ^ last-window
bind-key j choose-tree -swZ
bind-key M choose-tree -swZ "move-window -t '%%'"
bind-key P choose-tree -wZ "join-pane -t '%%'"
bind-key v capture-pane -b temp -S - \; save-buffer -b temp /tmp/tmux-buffer \; new-window "nvim +$ /tmp/tmux-buffer" \; delete-buffer -b temp
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-0 select-window -t 10
bind-key -n C-f new-window -n sessionizer "~/.local/bin/public/tmux-sessionizer" # thanks primeagain
# bind-key -n C-f if-shell "[ '#{pane_current_command}' = 'zsh' ]" \
#   "send-keys C-f" \
#   "new-window -n sessionizer \"~/.local/bin/public/tmux-sessionizer\""
# bind-key -n C-s switch-client -l

bind -n 'C-]' send-prefix

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-q send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'bash ~/.config/tmux/scripts/clip.sh'

# Status layout (colors come from pywal conf)
set -g status-left-length 40
set -g status-left " [#S]  "
set -g status-right ''
set -g status-right-length 20
set -g window-status-separator " "
set -g window-status-format " #I #W"
set -g window-status-current-format " #I*#W"
set -g monitor-activity on
set -g visual-activity off
set -g message-line 1

run-shell "~/.config/tmux/scripts/set_colors.sh"
source-file ~/.config/tmux/plugins.conf

bind-key -n C-h if -F '#{@pane-is-vim}' { send-keys C-h } { select-pane -L }
bind-key -n C-j if -F '#{@pane-is-vim}' { send-keys C-j } { select-pane -D }
bind-key -n C-k if -F '#{@pane-is-vim}' { send-keys C-k } { select-pane -U }
bind-key -n C-l if -F '#{@pane-is-vim}' { send-keys C-l } { select-pane -R }

# ghosty specific
set -s extended-keys on
set -s extended-keys-format csi-u   # tmux 3.5+
set -as terminal-features ",xterm-ghostty:extkeys"
