#!/usr/bin/env bash
set -euo pipefail

choice=$(
  nix-search-tv print --indexes home-manager |
    fzm --tty --dmenu -p "--margin='0,0,0,0' --preview 'nix-search-tv preview --indexes home-manager {}' --preview-window=right,55%,wrap --preview-label='docs' --preview-label-pos=1"
) || exit 0
[[ -z "$choice" ]] && exit 0

notify-send "NixOS Search Copied" "$choice"

printf "$choice" | wl-copy
