#!/usr/bin/env bash

set -euo pipefail

export PASSWORD_STORE_DIR="$HOME/.secrets/passwords"

export GPG_TTY=$(tty)

password_list=$(find "$PASSWORD_STORE_DIR" -name '*.otp.gpg' -type f -printf '%P\n' | sed 's|\.gpg$||' | sort || true)

[ -z "$password_list" ] && exit 0

choice=$(
  printf '%s\n' "$password_list" |
    fzm --dmenu --tty --dmenu -p "--prompt='select> ' --no-multi"
)

if ! password=$(pass show "$choice" 2>&1); then
  notify-send -u critical "Pass Error" "$password"
  read -p "Press enter..."
  exit 1
fi

password=$(pass otp "$choice" | head -n1 | tr -d '\n')

wl-copy <<<"$password"
sleep 0.1
cliphist delete-query "$password"

notify-send -i dialog-password "Password" "Copied to clipboard (clears in 20s)"
