#!/usr/bin/env bash
set -euo pipefail

choice=$(
  # list all remote gems (names only)
  gem search --remote --no-versions '' |
    fzm --tty --dmenu -p " --exact --margin='0,0,0,0' --preview 'gem info --remote {}' --scheme history --preview-window=top,55%,wrap --preview-label='docs' --preview-label-pos=1"
)

notify-send "RubyGems: gem copied" "$choice"

printf '%s' "$choice" | wl-copy
