-- Luavim.lsp.config.rust = {
-- 	cmd = { "rust-analyzer" },
-- 	filetypes = { "rust" },
-- 	root_markers = { "Cargo.toml" },
-- 	settings = {
-- 		["rust-analyzer"] = {
-- 			check = {
-- 				command = "clippy",
-- 			},
-- 		},
-- 	},
-- }
--
-- vim.lsp.enable("rust")
