#!/usr/bin/env bash

declare -A MONTHS=(
  [01]="❄️" [02]="👵🏻" [03]="👩🏻" [04]="🪻" [05]="🌼" [06]="☀️"
  [07]="🎂" [08]="🍉" [09]="🍂" [10]="🫖" [11]="☃️" [12]="🎄"
)

month=$(date +%m)
ironbar var set date_emoji "${MONTHS[$month]}"
