return {
  "folke/todo-comments.nvim",
  event = "VeryLazy",
  dependencies = { "nvim-lua/plenary.nvim" },
  opts = {
    signs = true,
    keywords = {
      TODO  = { icon = "", color = "info" },
      NOTE  = { icon = "", color = "info",  alt = { "INFO" } },
      FIX   = { icon = "", color = "info", alt = { "FIXME", "BUG" } },
      WARN  = { icon = "", color = "info", alt = { "WARNING" } },
      HACK  = { icon = "", color = "info" },
      PERF  = { icon = "", color = "info", alt = { "OPTIM", "PERF" } },
      CHORE = { icon = "󰚰", color = "info" },
      WIP   = { icon = "󰦖", color = "info" },
      TEST  = { icon = "󰙨", color = "info" },
      REVIEW= { icon = "", color = "info" },
    },
    highlight = {
      multiline = false,
      before = "",
      after = "fg",
      keyword = "wide",
      pattern = [[.*<(KEYWORDS)\s*:?]],
    },
    search = { pattern = [[\b(KEYWORDS):?]] },
  },
  keys = {
    { "]t", function() require("todo-comments").jump_next() end, desc = "Next TODO" },
    { "[t", function() require("todo-comments").jump_prev() end, desc = "Prev TODO" },
    { "<leader>tt", "<cmd>TodoTelescope<cr>", desc = "Todos (Telescope)" },
    { "<leader>tq", "<cmd>TodoQuickFix<cr>", desc = "Todos (QuickFix)" },
    { "<leader>tr", "<cmd>TodoTrouble<cr>",  desc = "Todos (Trouble)" },
  },
}
