source $HOME/.cache/wal/colors.sh
source $HOME/.config/zsh/modules/path.zsh

source $HOME/.config/zsh/modules/fzf.zsh

# source $HOME/.config/zsh/modules/colors.zsh
source $HOME/.config/zsh/modules/functions.zsh
source $HOME/.config/zsh/modules/autocomplete.zsh
source $HOME/.config/zsh/modules/ls_colors.zsh
source $HOME/.config/zsh/modules/diff_so_fancy.zsh
source $HOME/.config/zsh/modules/prompt.zsh
source $HOME/.config/zsh/modules/direnv.zsh
source $HOME/.config/zsh/modules/history.zsh
source $HOME/.config/zsh/modules/jobs.zsh
source $HOME/.config/zsh/modules/search.zsh
source $HOME/.config/zsh/modules/settings.zsh
source $HOME/.config/zsh/modules/bat.zsh
source $HOME/.config/zsh/modules/git.zsh
source $HOME/.config/zsh/modules/nix.zsh
source $HOME/.config/zsh/modules/edit_command_line.zsh
source $HOME/.config/zsh/modules/hotkeys.zsh
source $HOME/.config/zsh/modules/aliases.zsh
source $HOME/.config/zsh/modules/veracrypt.zsh
source $HOME/.config/zsh/modules/media.zsh
source $HOME/.config/zsh/modules/exports.zsh
source $HOME/.config/zsh/modules/xdg-open.zsh
source $HOME/.config/zsh/modules/python.zsh
