source ~/.zprofile

source $HOME/.cache/wal/colors-zsh.sh

source $HOME/.config/zsh/modules/path.zsh
source $HOME/.config/zsh/modules/hotkeys.zsh

# order is important
source $HOME/.config/zsh/modules/suggestions.zsh
source $HOME/.config/zsh/modules/fzf.zsh

source $HOME/.config/zsh/modules/exports.zsh
source $HOME/.config/zsh/modules/functions.zsh
# source $HOME/.config/zsh/modules/ls_colors.zsh
source $HOME/.config/zsh/modules/diff_so_fancy.zsh
source $HOME/.config/zsh/modules/prompt.zsh
source $HOME/.config/zsh/modules/direnv.zsh
source $HOME/.config/zsh/modules/history.zsh
source $HOME/.config/zsh/modules/jobs.zsh
source $HOME/.config/zsh/modules/search.zsh
source $HOME/.config/zsh/modules/settings.zsh
source $HOME/.config/zsh/modules/bat.zsh
source $HOME/.config/zsh/modules/git.zsh
source $HOME/.config/zsh/modules/nix.zsh
source $HOME/.config/zsh/modules/edit_command_line.zsh
source $HOME/.config/zsh/modules/aliases.zsh
source $HOME/.config/zsh/modules/veracrypt.zsh
source $HOME/.config/zsh/modules/luks.zsh
source $HOME/.config/zsh/modules/media.zsh
source $HOME/.config/zsh/modules/xdg-open.zsh
source $HOME/.config/zsh/modules/python.zsh
# source $HOME/.config/zsh/modules/pywal.zsh
source $HOME/.config/zsh/modules/tmux.zsh
source $HOME/.config/zsh/modules/yazi.zsh
source $HOME/.config/zsh/modules/gpg.zsh
# source $HOME/.config/zsh/modules/colors.zsh
# source $HOME/.config/zsh/modules/base16.zsh

if [[ -n "$TMUX" ]]; then
  export TERM="tmux-256color"
else
  export TERM="xterm-256color"
fi

# Block garbage escape sequences from becoming commands
preexec() {
  [[ "$1" =~ '^_G|Ptmux|^\[' ]] && return 1
}

bindkey -s ';f' 'nvim -c "FzfLua files"\n'
bindkey -s '^f' 'tmux attach \; run-shell "tmux send-keys C-f"\n'

export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
