backend = "glx";
vsync = false;

shadow = false;
fading = false;
blur-method = "none";
corner-radius = 0;

unredir-fullscreen-windows = true;
use-damage = true;          

detect-client-opacity = false;
detect-rounded-corners = false;
