#!/usr/bin/env python3

from datetime import datetime

now = datetime.now()

def quartal():
    m = now.month
    return (m - 1) // 3 + 1

def iso_week():
    return now.isocalendar().week


#  Q3, W39, 09  23 Sep  16:25

print(f" (Q{quartal()}, W{iso_week():02d}, {now:%m})  ({now:%B} - {now:%d})  ({now:%H}:{now:%m}) ")
