#!/usr/bin/env bash
set -euo pipefail

: "${KITTY_LAUNCHER_SOCKET_PATH:=/tmp/kitty-launcher}"
: "${LAUNCHER_SCRIPTS_PATH:=$HOME/.config/scripts/menu}"

kitty -o allow_remote_control=yes \
  --listen-on "unix:${KITTY_LAUNCHER_SOCKET_PATH}" \
	-o font_size=14 \
	--single-instance \
	--class launcher \
	bash -lc "$LAUNCHER_SCRIPTS_PATH/launch-menu"
