#!/usr/bin/env bash
set -euo pipefail

source "$USER_SCRIPTS_PATH/menu/helpers/fzf-with-options"

SCRIPT_DIR="$HOME/.config/scripts/menu/options"

OPTIONS=(
  "applications:󰣆 Applications"
  "nix-packages: Nix Search Packages"
  "nix-options: Nix Search Options"
  "nix-switch: Nix Switch"
  #"bookmarks:󰖟 Browser Bookmarks"
  #"history:󰖟 Browser History"
  #"pass: Passwords"
  #"pass:2FAuthnetication"
  "kill:󰧻 Kill Program"
  #"connect-bluetooth: Connect Bluetooth"
  #"connect-bluetooth:󰖩 Connect Wi-Fi"
  #"search-youtube:󰕧 Search Youtube"
)

choice="$(
  printf '%s\0' "${OPTIONS[@]}" \
    | fzf --read0 --delimiter=':' --with-nth=2
)" || exit 0

key="${choice%%:*}"
script="${SCRIPT_DIR}/${key}"

if [[ -x "$script" ]]; then
  exec "$script"
elif [[ -f "$script" ]]; then
  exec bash "$script"
else
  printf "script not found: %s\n" "$script" >&2
  exit 1
fi
