#!/usr/bin/env bash
sep=$'\034'   # field separator required by sway-launcher-desktop

OPTIONS=(
  "applications:󰣆 Applications"
  "nix-packages: Nix Search Packages"
  "nix-options: Nix Options"
  "nix-switch: Nix Switch"
  "bookmarks:󰖟 Browser Bookmarks"
  "history:󰖟 Browser History"
  "pass: Passwords"
  "pass:2FAuthnetication"
  "kill:󰧻 Kill Program"
  "connect-bluetooth: Connect Bluetooth"
  "connect-bluetooth:󰖩 Connect Wi-Fi"
  "search-youtube:󰕧 Search Youtube"
)

last=$(( ${#OPTIONS[@]} - 1 ))

for i in "${!OPTIONS[@]}"; do
  IFS=':' read -r key label <<<"${OPTIONS[i]}"

  if (( i == last )); then
    printf '%s%smainmenu%s%s' "$key" "$sep" "$sep" "$label"
  else
    printf '%s%smainmenu%s%s\n' "$key" "$sep" "$sep" "$label"
  fi
done
