#!/usr/bin/env python3
import calendar
import sys
from datetime import datetime

MONTH_DICTIONARY = {
    1:  "❄️", # January
    2:  "👵🏻", # February
    3:  "👩🏻", # March
    4:  "🪻", # April
    5:  "🌼", # May
    6:  "☀️", # June
    7:  "🎂", # July
    8:  "🍉", # August
    9:  "🍂", # September
    10: "🫖", # October
    11: "☃️", # November
    12: "🎄", # December
}

class NeuroDivergentTime:
    def __init__(self):
        self.date = datetime.now()
        self.format = sys.argv[1]

    def print(self):
        match self.format:
            case "neuro":
                self.neuro_string()
            case "month":
                self.month_string()
            case "time":
                self.time_string()
            case _:
                self.regular_string()

    def neuro_string(self, version=2):
        if version == 1:
            print(f" Q{self.quartal()} W{self.iso_week():02d}/52 {self.date:%m}/12 {self.date:%d}/{self.days_in_month()}")
        else:
            print(f" Q{self.quartal()} W{self.iso_week():02d}/52 {self.date:%d}/{self.days_in_month()}")

    def month_string(self, version=2):
        if version == 1:
            print(f"{self.get_month_emoji()} {self.date:%B}")
        else:
            print(f"{self.get_month_emoji()} {self.date:%m}/12 {self.date:%B}")


    def time_string(self):
        print(f"{self.date:%H}:{self.date:%M}")

    def regular_string(self):
        print(f" Q{self.quartal()}, W{self.iso_week():02d}, {self.date:%m} ({self.date:%B} - {self.date:%d}) {self.date:%H}:{self.date:%m} ")

    # private

    def quartal(self):
        return (self.date.month - 1) // 3 + 1

    def iso_week(self):
        return self.date.isocalendar().week

    def days_in_month(self):
        return calendar.monthrange(self.date.year, self.date.month)[1]

    def get_month_emoji(self):
        return MONTH_DICTIONARY[self.date.month]




service = NeuroDivergentTime()
service.print()