openweathermap: ENC[AES256_GCM,data:g8d+LqELnfXIs9WOkuSkbLzMdy5qOiTill29bt0m2YU=,iv:XSmA1UgCAmYFwBUyyJ9dnkcTNxf6PJzT6+oM6sqIEnk=,tag:62lctQW+uqOIU/MG6NXTUw==,type:str]
email: ENC[AES256_GCM,data:18eU5ig9PlF+/PYZ343/korjNfH23lI=,iv:PlGH2BfvHjIOJ6Y27i+AKyIbsMEX5nvCpME4gdMKU+U=,tag:2g9jOQOtVa4EcdT4h1e5xg==,type:str]
searx_secret_key: ENC[AES256_GCM,data:wi1d5VLHCBBkaOMYIWKJVFDL3P++ieGuLsNBh3Trh0Nv6fw40lUiRSFBL+iKWgM8u5fHe5OU/qxdo+KfCQDowQ==,iv:9I8fyL7clnGRgZTBc1XROtemna74kRAebRmWkBJ1nfw=,tag:06tCQlsiIz8sdNc7jIzKIw==,type:str]
sops:
    age:
        - recipient: age1d00rcmten5elkg54252vr3rkh8vksnlaf8ur92ddm9k5zsya4cqq2wc37f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UGNlcWdMd2ZRWmNMSjZY
            bnpEenlocWR4T3ZzR1cvc0wxdGFBTmNtL0dVCmgwOUFJN1c4ZjhPRm5QRnpacDlZ
            cnhpSWRKMzYxNENtREMvVmJOQWg1ZmcKLS0tIDVaazh6bGpzb3o2TkNSN3JHNlVw
            OTJCeHFodkpGS3Z4eTdGWVZKZEhWeUkKwy88Le8Cn/x0JUdeG8TS3e57TtoKnq8x
            jD+IebHSGJFMu5pAKD4h/oTfxpheQHU97GdGvmGCreSmpaS+2FADjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T16:18:46Z"
    mac: ENC[AES256_GCM,data:bt9Riu2jRptT8Fcs146ayD5rrW8QGili2mCb7kZ22W1w6uDVwThRiQrG/nFoVDrfHq+iIEuTKyGIvg3bZH6ix90LzGnfFM7GakiDnOwZuy472DV2gDG+RB2ya2pMrtGVWMWUS8OLK9jipcJBwsLR2AWh0JryDi8kM2A4AMbi2nc=,iv:PgEuibQaYUszAgO2BtUb6mBq69WbR1TyTbuFuaunFdc=,tag:orqIxQLfQsViZBn1h8vpjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
