openweathermap: ENC[AES256_GCM,data:g8d+LqELnfXIs9WOkuSkbLzMdy5qOiTill29bt0m2YU=,iv:XSmA1UgCAmYFwBUyyJ9dnkcTNxf6PJzT6+oM6sqIEnk=,tag:62lctQW+uqOIU/MG6NXTUw==,type:str]
email: ENC[AES256_GCM,data:MLpg6J2GgbcByoBeLX2/wMCzSgA3N6A=,iv:v4FmLVF5P28NnG/JgLdtSXcinRmQQAkUt+drMCBvl3g=,tag:8HmhKRKsrm5Dc+/4V6j7Yw==,type:str]
khole:
    ssh:
        key: ENC[AES256_GCM,data:vEpluz3wkvKfY/WqM4WA2ReMNXKORac3OQPs2yXVGf+zcR81akI7vVpt9HfAkhzb1UpAvIV+LlNMrmjmdfOaQ0fBOSLtkhbikB2yn/RdrQ5vOC7hEeUs0HKlzFy2ShB5HY6DSK6fG3Drc2ZR4YR/sgYuLz5Dg9gngX1ICl7TCR7N91cQgv6Ww1nNffETM8lcqnP4/xFyZMG8e/ps43XM197sDGbGsDkZMkdVySjHjfxcuZCxRInRcV9Z+HswVitg4CKI/5PEunb9zWOJ/T8qm0ZhOf9pvHYcI8Ge0Mu/jkrTlQGHPPz+Ov4DTPFz5RMM7mxVMQR33LxxP56POfK4zKQbdiYhAdqpmQqShCLbJ0tIQeSsz5OW7TNsUtGJ9ZYVlbx08BtkPjpyjiIywVcHf+1LRA/lhEySr7HfpHR7wwrC/uvCnjSETTSQAFsEc2ORT7rW9yvPJbbxARe/OjMnoXMJ0sbHsvTb0iY0Reilq23gFcJBGqWkx3B0Kp47JVR4dxqQlZxjbEWJBwgiz0UbwlRhbBOyY5pBYlaIuGJ5jN3C6X0my54WwpiHDPYpjBoSX4z9781VV4rOJqDH5+OFQCko0l82+jOe03AkLAG5w9aieRKegIuWRounPVnpQYTvunDq7/5dfUoUcotm12/amXV9jQdipwEXzyBAMUaEBKyocTLzohN2Flp7AR8FLhwFB+DlP7YsfJx7UEBcxQcUwQDiHseZiczZiCU0SLNDByYmOmOEwmfa00Jt7X9Oox+NFgUQUd0EICMW0Yd92P3eYLdxZsyj/Wrh57pZDSABGGr7l1n7/hHiCUWpSxcQF3d5Ob+dq36u6mmjJUwkf6QnLZJwSzG/gCH0L+rEtmK6L1O1F+NxojVhFMzknOhpFTOCEw6R2nJ9HVCQ4b8jp4d//9+P4U3W7xA9aekVDAz9Ho0MXF9QQOhCYk+ulFCD/eyR3Ac50dzyH9M3loJJuymJS1BB57fPuFrTqpA=,iv:YQK0SxIYte8S7cxSuEv6AmIWJqdLGRtpjsB4I450k+w=,tag:AMXQeeNYNEBZdhZjpku6PQ==,type:str]
    user:
        password: ENC[AES256_GCM,data:hZ4JuL3MTTkIZYZE/kB5JutoZKE=,iv:yYzOGKcNB7shnllPo9DJx1rK/k+NpDg2tCfbn7LUYWY=,tag:8pQMZQ5LuIY7i62h+ydx5Q==,type:str]
    pihole:
        password: ENC[AES256_GCM,data:h+XeTKILlZQTwNjV0pih8vne7xo=,iv:Cnk1cZjcldDbngmk8GLTOychpVwQ/8lcxIFMYuBx1NA=,tag:61Fx5uAxZQ9gqambdq2uPA==,type:str]
sops:
    age:
        - recipient: age1d00rcmten5elkg54252vr3rkh8vksnlaf8ur92ddm9k5zsya4cqq2wc37f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UGNlcWdMd2ZRWmNMSjZY
            bnpEenlocWR4T3ZzR1cvc0wxdGFBTmNtL0dVCmgwOUFJN1c4ZjhPRm5QRnpacDlZ
            cnhpSWRKMzYxNENtREMvVmJOQWg1ZmcKLS0tIDVaazh6bGpzb3o2TkNSN3JHNlVw
            OTJCeHFodkpGS3Z4eTdGWVZKZEhWeUkKwy88Le8Cn/x0JUdeG8TS3e57TtoKnq8x
            jD+IebHSGJFMu5pAKD4h/oTfxpheQHU97GdGvmGCreSmpaS+2FADjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T17:00:20Z"
    mac: ENC[AES256_GCM,data:SwmJ690D0DV2m9KTYe5r/hiS3ZGMpV2yVQ28WbG5eGtB44k15e+6cEN3cWDKmGEfoMN2pPQn7Hhb9EgEQ7kWu/y1m+mDwWPjhS5YDCONyOIGbCX/hpTIbDogiXNy6qRCFFj4mBf0csfFBSy4V/rMmClIkVGudj2b/igUiLRdKV0=,iv:yEeEPnpY1KHcukai1d3uzA3BhylR7/SVMVesUJ3o5og=,tag:FPJc/K8oVR0k2IuHMlObzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
