openweathermap: ENC[AES256_GCM,data:g8d+LqELnfXIs9WOkuSkbLzMdy5qOiTill29bt0m2YU=,iv:XSmA1UgCAmYFwBUyyJ9dnkcTNxf6PJzT6+oM6sqIEnk=,tag:62lctQW+uqOIU/MG6NXTUw==,type:str]
sops:
    age:
        - recipient: age1d00rcmten5elkg54252vr3rkh8vksnlaf8ur92ddm9k5zsya4cqq2wc37f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UGNlcWdMd2ZRWmNMSjZY
            bnpEenlocWR4T3ZzR1cvc0wxdGFBTmNtL0dVCmgwOUFJN1c4ZjhPRm5QRnpacDlZ
            cnhpSWRKMzYxNENtREMvVmJOQWg1ZmcKLS0tIDVaazh6bGpzb3o2TkNSN3JHNlVw
            OTJCeHFodkpGS3Z4eTdGWVZKZEhWeUkKwy88Le8Cn/x0JUdeG8TS3e57TtoKnq8x
            jD+IebHSGJFMu5pAKD4h/oTfxpheQHU97GdGvmGCreSmpaS+2FADjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T13:46:31Z"
    mac: ENC[AES256_GCM,data:Vuojrt9+lNhXO7jQ9lqBSOrMxIe9BOqUWhNr4pLF+0KTxrsFc/0fxbAnCLzvKYMuJvzD6MLYiaUC4ySFL4FxfJO5j60GD2X/6ZtBMG5iRKX1piMNhpeK/+Xfx+kiG1z6axO0RcX9Eio3ZBAHDW6S/t29sNqdkbO82gdyFzudBgQ=,iv:82aViHj0VdGFDBTUsW8uDyJiI5uN1M3WSSXzji2qMaI=,tag:cC4xRsZOv870AKqnlEBR6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
