openweathermap: ENC[AES256_GCM,data:g8d+LqELnfXIs9WOkuSkbLzMdy5qOiTill29bt0m2YU=,iv:XSmA1UgCAmYFwBUyyJ9dnkcTNxf6PJzT6+oM6sqIEnk=,tag:62lctQW+uqOIU/MG6NXTUw==,type:str]
email: ENC[AES256_GCM,data:MLpg6J2GgbcByoBeLX2/wMCzSgA3N6A=,iv:v4FmLVF5P28NnG/JgLdtSXcinRmQQAkUt+drMCBvl3g=,tag:8HmhKRKsrm5Dc+/4V6j7Yw==,type:str]
sops:
    age:
        - recipient: age1d00rcmten5elkg54252vr3rkh8vksnlaf8ur92ddm9k5zsya4cqq2wc37f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UGNlcWdMd2ZRWmNMSjZY
            bnpEenlocWR4T3ZzR1cvc0wxdGFBTmNtL0dVCmgwOUFJN1c4ZjhPRm5QRnpacDlZ
            cnhpSWRKMzYxNENtREMvVmJOQWg1ZmcKLS0tIDVaazh6bGpzb3o2TkNSN3JHNlVw
            OTJCeHFodkpGS3Z4eTdGWVZKZEhWeUkKwy88Le8Cn/x0JUdeG8TS3e57TtoKnq8x
            jD+IebHSGJFMu5pAKD4h/oTfxpheQHU97GdGvmGCreSmpaS+2FADjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T09:29:08Z"
    mac: ENC[AES256_GCM,data:+DZlcG8kElOfw5wJdClfJb6fv/t5dykxULyTH4vQv2NwjYc3C9xlTqRZI0NVFj9aKEqbPzxNvtBLjNuGJwBmzvJwGPntHoK5bzxD+PSlJao1O/2HBYhucqSKlTaj0GIbd+fa3R5tofOQVT9IRnX9xU6KR7SxpVaiR746tdEga10=,iv:RpGKC/h7Xe+Tg8I0XMIUTo3/6axDgPe2fPhTk0zp3xE=,tag:NatH5KxFk06fRV1wjWKJkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
